services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    env_file:
      - .env
  app:
    build: .
    command: python main.py
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
